language: rust
env:
  - RUSTFLAGS="-D warnings"
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly 
      script: cargo test --all --verbose --features compiletest_rs
  allow_failures:
    - rust: nightly
