[package]
name = "rlua"
version = "0.4.2"
authors = ["kyren <catherine@chucklefish.org>"]
description = "High level bindings to Lua 5.3"
repository = "github.com/chucklefish/rlua"
documentation = "docs.rs/rlua"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

[build-dependencies]
gcc = "0.3"

[dependencies]
hlist-macro = "0.1"
error-chain = "0.10"
