[package]
name = "rlua"
version = "0.8.0"
authors = ["kyren <catherine@chucklefish.org>"]
description = "High level bindings to Lua 5.3"
repository = "https://github.com/chucklefish/rlua"
documentation = "https://docs.rs/rlua"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

[build-dependencies]
gcc = "0.3"

[dependencies]
hlist-macro = "0.1"
