[package]
name = "rlua"
version = "0.15.3"
authors = ["kyren <catherine@chucklefish.org>"]
description = "High level bindings to Lua 5.3"
repository = "https://github.com/chucklefish/rlua"
documentation = "https://docs.rs/rlua"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

# [badges]
# travis-ci = { repository = "chucklefish/rlua", branch = "master" }

[dependencies]
libc = { version = "0.2" }
failure = { version = "0.1.2" }
num-traits = { version = "0.2.6" }
compiletest_rs = { version = "0.3", optional = true }

[build-dependencies]
cc = "1.0"
pkg-config = "0.3.11"

[dev-dependencies]
rustyline = "2.0.0"
criterion = "0.2.0"

[[bench]]
name = "benchmark"
harness = false
