[package]
name = "mlua"
version = "0.15.3"
authors = ["Aleksandr Orlenko <zxteam@pm.me>", "kyren <catherine@chucklefish.org>"]
edition = "2018"
description = "High level bindings to Lua 5.3"
repository = "https://github.com/khvzak/mlua"
documentation = "https://docs.rs/mlua"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

# [badges]
# travis-ci = { repository = "khvzak/mlua", branch = "master" }

[dependencies]
libc = { version = "0.2" }
num-traits = { version = "0.2.6" }
bstr = { version = "0.2", features = ["std"], default_features = false }

[build-dependencies]
cc = { version = "1.0" }
pkg-config = { version = "0.3.11" }

[dev-dependencies]
rustyline = "5.0"
criterion = "0.2.0"

[[bench]]
name = "benchmark"
harness = false
