[package]
name = "rlua"
version = "0.2.0"
authors = ["kyren <catherine@chucklefish.org>"]
repository = "https://github.com/chucklefish/rlua"
description = "High level bindings to Lua 5.3"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

[build-dependencies]
gcc = "0.3"

[dependencies]
hlist-macro = "0.1"
error-chain = "0.10"
