[package]
name = "rlua"
version = "0.1.0"
authors = ["kyren <catherine@chucklefish.org>"]
repository = "https://github.com/chucklefish/rlua"
description = "High level bindings to Lua 5.3"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

[build-dependencies]
gcc = "*"

[dependencies]
error-chain = "*"
