[package]
name = "rlua"
version = "0.12.2"
authors = ["kyren <catherine@chucklefish.org>"]
description = "High level bindings to Lua 5.3"
repository = "https://github.com/chucklefish/rlua"
documentation = "https://docs.rs/rlua"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

[badges]
travis-ci = { repository = "chucklefish/rlua", branch = "master" }

[features]
default = ["builtin-lua"]
# Builds the correct version of Lua 5.3 inside the crate. If you want to link a
# specialized version of lua into your binary, you can disable this feature to
# do that, but care must be taken.  `rlua` makes at least the following
# assumptions about the linked lua library:
#   * LUA_INTEGER is long long
#   * LUA_NUMBER as double
#   * LUA_EXTRASPACE is sizeof(void*)
builtin-lua = ["gcc"]
# Error handling is completely broken on windows with
# https://github.com/rust-lang/rust/pull/46833 merged, and this includes stable
# rustc 1.24.0+.  This feature fixes error handling on windows, but requires
# nightly!  See https://github.com/rust-lang/rust/issues/48251 and
# https://github.com/chucklefish/rlua/issues/71 for details.
unwind = []

[dependencies]
libc = { version = "0.2" }
failure = { version = "0.1.1" }
compiletest_rs = { version = "0.3", optional = true }

[build-dependencies]
gcc = { version = "0.3.52", optional = true }

[dev-dependencies]
rustyline = "1.0.0"